modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="remolicrack_vanilla_plus"
version="1.0.0"
displayName="Remolicrack's Vanilla+"
displayURL="https://modrinth.com/mod/remolicracks_vanilla_plus"
logoFile="logo.png"
credits="Created by Remolicrack"
authors="Remolicrack"

[[dependencies.remolicrack_vanilla_plus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




